import { Testimonial } from './types';

export const TESTIMONIALS_ES: Testimonial[] = [
  { name: "Cristián Valenzuela F.", role: "Expert UX/UI", company: "Gasco", text: "Francisco fue lejos uno de los mejores Scrum Master que hemos tenido. Su habilidad para encontrar soluciones a problemas es fenomenal." },
  { name: "Paulina Carvajal M.", role: "Ingeniera Civil Industrial", company: "Gasco", text: "Es un profesional de alto nivel, su especialidad como Scrum Master logra que los equipos mantengan un ritmo excepcional de trabajo." },
  { name: "Iván Villarroel", role: "Backend / AI Engineer", company: "Gasco", text: "Inspira a los equipos como pocos pueden. Su estilo cordial permite enfocar a diversas personalidades hacia el objetivo del producto." },
  { name: "Flavio Figueroa", role: "Ingeniero Mecánico", company: "Gasco", text: "Manejó de forma muy eficiente el control del proyecto, sin permitir que nada quedase en el aire. El profesional mejor organizado." },
  { name: "Bruno Rimassa", role: "Product Owner", company: "Gasco", text: "De mis 7 años trabajando con metodologías ágiles, Francisco es uno de los mejores SM. Muy proactivo, resolutor y excelente gestor." },
  { name: "Miguel González A.", role: "Software Engineer / Tech Lead", company: "Gasco", text: "Destaca por sobre los demás. Capaz de destrabar bloqueantes en un dos por tres, y hacer dinámicas que logran estrechar lazos." },
  { name: "José Luis Paredes Z.", role: "Corporate Innovation", company: "Gasco", text: "Excelente profesional capaz de leer las múltiples solicitudes de los usuarios y traducirlo en lo que realmente necesitan." },
  { name: "Elizabeth Farías V.", role: "QA Engineer", company: "Gasco", text: "Las reuniones de equipo nunca fueron aburridas, motivando a cada uno. Empático, con gran paciencia y siempre dispuesto a ayudar." },
  { name: "Stiwart Tobías A.", role: "CEO & Full Stack Dev", company: "Gasco", text: "Líder excepcional y Scrum Master altamente competente. Su experiencia fue fundamental para el éxito de nuestros desafiantes proyectos." },
  { name: "Erika Ramirez Q.", role: "Product Designer UX/UI", company: "Gasco", text: "Líder innato que con su proactividad encuentra oportunidades de mejora. Todo un privilegio trabajar de la mano de Francisco." },
  { name: "Pablo Leiva", role: "Project Manager", company: "Cencosud Scotiabank", text: "Muy preocupado de sus equipos técnica y humanamente. Un excelente líder y gran conocedor para abordar cada desafío." },
  { name: "Zulay Sánchez D.", role: "Change Management Lead", company: "RedSalud CCHC", text: "Promueve espacios para la innovación enfocado a mejora continua. Trabajar con él fue muy grato; está muy orientado a objetivos." },
  { name: "Marianella Rojas", role: "Systems Engineer", company: "Cencosud Scotiabank", text: "Profesional de alto desempeño, enfocado a logros. Destaca su capacidad de adaptación y manejo ágil ante situaciones muy difíciles." },
  { name: "Deyanny Prado R.", role: "Product Owner", company: "Cencosud Scotiabank", text: "Profesional siempre motivado al aprendizaje, abierto a los cambios. Siempre demostró gran empatía, profesionalismo y mística de trabajo." },
  { name: "Juan Carlos Toro", role: "QA Lead / Service Delivery", company: "Cencosud Scotiabank", text: "Excelente colaborador ayudando a destrabar y agilizar soluciones. Siempre pone su conocimiento técnico y metodológico a disposición." },
  { name: "Rafael Moya M.", role: "Org. Development Head", company: "Cencosud Scotiabank", text: "Comprometido y muy consciente de estimular siempre a quienes forman parte del equipo, logrando relaciones de trabajo sanas." },
  { name: "Percy Ross", role: "IT Project Manager", company: "Cencosud Scotiabank", text: "Gran líder, motivador y apañador, buscando siempre la sinergia para avanzar. Demuestra sólido conocimiento tecnológico de vanguardia." },
  { name: "Richard Barbera", role: "CTO / Director Of Engineering", company: "Cencosud Scotiabank", text: "Metódico, organizado y tremendamente dedicado. Completamente recomendable para cualquier tipo de proyecto de alto impacto." },
  { name: "Reinaldo Gonzalez", role: "Head of Modernization", company: "Cencosud Scotiabank", text: "Siempre actualizado con las últimas metodologías. Muy buen manejo de equipo, innovador, con mucho talento y muy responsable." },
  { name: "William Gómez", role: "Technical Lead", company: "Innomar Ltda", text: "Gran capacidad analítica, mentor seguro que acompaña hacia el éxito cualquier proyecto facilitando situaciones realmente adversas." },
  { name: "Gonzalo Sánchez", role: "Full Stack Developer", company: "Cencosud S.A.", text: "Muy responsable y con un altísimo dominio impecable de la metodología ágil de trabajo." },
  { name: "Paulina Barrera B.", role: "Product Manager", company: "Cencosud Scotiabank", text: "Un tremendo profesional, muy proactivo, con fuerte motivación a innovar y ampliar constantemente dentro de sus equipos de desarrollo." }
];

export const TESTIMONIALS_EN: Testimonial[] = [
  { name: "Cristián Valenzuela", role: "Expert UX/UI", company: "Gasco", text: "Francisco was by far one of the best Scrum Masters we've had. His ability to find solutions is phenomenal." },
  { name: "Paulina Carvajal", role: "Industrial Engineer", company: "Gasco", text: "High-level professional; his expertise as a Scrum Master helps teams maintain an exceptional working pace." },
  { name: "Iván Villarroel", role: "Backend / AI Engineer", company: "Gasco", text: "He inspires teams like few can. His cordial style guides diverse personalities straight towards the product's goal." },
  { name: "Flavio Figueroa", role: "Mechanical Engineer", company: "Gasco", text: "He managed project control extremely efficiently, never letting anything slip through. The most organized professional." },
  { name: "Bruno Rimassa", role: "Product Owner", company: "Gasco", text: "In my 7 years with agile, he is one of the best SMs I've worked with. Highly proactive, resolving, and a great manager." },
  { name: "Miguel González", role: "Software Engineer / Tech Lead", company: "Gasco", text: "He stands out above the rest. Capable of removing blockers efficiently and running dynamics that bond the team." },
  { name: "José Luis Paredes", role: "Corporate Innovation", company: "Gasco", text: "Excellent top professional capable of reading users' complex requests and translating them into exactly what they need." },
  { name: "Elizabeth Farías", role: "QA Engineer", company: "Gasco", text: "Team meetings were never boring. Empathetic, extremely patient, and always willing to help and motivate everyone." },
  { name: "Stiwart Tobías", role: "CEO & Full Stack Dev", company: "Gasco", text: "An exceptional leader and highly competent Scrum Master. His expertise was vital to the success of our challenging projects." },
  { name: "Erika Ramirez", role: "Product Designer UX/UI", company: "Gasco", text: "An innate leader who always finds improvement opportunities. Simply a privilege to work alongside Francisco." },
  { name: "Pablo Leiva", role: "Project Manager", company: "Cencosud Scotiabank", text: "Deeply caring for his teams both technically and humanely. An excellent leader equipped to tackle any project challenge." },
  { name: "Zulay Sánchez", role: "Change Management Lead", company: "RedSalud CCHC", text: "He promotes spaces for innovation and continuous improvement. Working with him was great; he is truly goal-oriented." },
  { name: "Marianella Rojas", role: "Systems Engineer", company: "Cencosud Scotiabank", text: "High-performance professional. His ability to adapt and manage conflicts in difficult agile situations is outstanding." },
  { name: "Deyanny Prado", role: "Product Owner", company: "Cencosud Scotiabank", text: "A professional driven by learning and open to changes. He constantly displayed empathy, professionalism, and work ethic." },
  { name: "Juan Carlos Toro", role: "QA Lead / Service Delivery", company: "Cencosud Scotiabank", text: "Great collaborator in clearing blockers. He always puts his deep technical and methodological knowledge at the team's disposal." },
  { name: "Rafael Moya", role: "Org. Development Head", company: "Cencosud Scotiabank", text: "Committed to always keeping the team stimulated, thus achieving an incredibly healthy working dynamic and optimal results." },
  { name: "Percy Ross", role: "IT Project Manager", company: "Cencosud Scotiabank", text: "Great motivator and leader, always seeking team synergy to move forward, showing solid knowledge in cutting-edge tech." },
  { name: "Richard Barbera", role: "CTO / Director Of Engineering", company: "Cencosud Scotiabank", text: "Methodical, organized, and deeply dedicated team-player. Highly recommended for any type of high-impact technical project." },
  { name: "Reinaldo Gonzalez", role: "Head of Modernization", company: "Cencosud Scotiabank", text: "Always updated with the newest methodologies. Handles teams excellently; he is innovative, deeply talented, and responsible." },
  { name: "William Gómez", role: "Technical Lead", company: "Innomar Ltda", text: "Great analytical skills. A confident mentor who guides projects to success, easily navigating really complex situations." },
  { name: "Gonzalo Sánchez", role: "Full Stack Developer", company: "Cencosud S.A.", text: "Very responsible and displays an absolute, flawless mastery of agile methodologies." },
  { name: "Paulina Barrera", role: "Product Manager", company: "Cencosud Scotiabank", text: "A tremendous self-starter professional, strongly motivated to innovate and consistently bring new ideas into his tech teams." }
];

export const TESTIMONIALS_PT: Testimonial[] = [
  { name: "Cristián Valenzuela", role: "Expert UX/UI", company: "Gasco", text: "Francisco foi sem dúvida um dos melhores Scrum Masters que tivemos. Sua capacidade de solução é fenomenal." },
  { name: "Paulina Carvajal", role: "Engenheira Industrial", company: "Gasco", text: "Um profissional de alto nível; sua especialidade como Scrum Master mantém um ritmo excepcional de trabalho nas equipes." },
  { name: "Iván Villarroel", role: "Engenheiro Backend / IA", company: "Gasco", text: "Ele inspira equipes como poucos. Seu estilo cordial permite alinhar diversas personalidades rumo ao objetivo do produto." },
  { name: "Flavio Figueroa", role: "Engenheiro Mecânico", company: "Gasco", text: "Gerenciou o controle do projeto de forma muito eficiente, sem deixar nada solto. É o profissional mais organizado que conheço." },
  { name: "Bruno Rimassa", role: "Product Owner", company: "Gasco", text: "Em meus 7 anos de agile, Francisco é um dos melhores SMs. Altamente pró-ativo, com excelente resolução e gestão de equipe." },
  { name: "Miguel González", role: "Engenheiro de Software", company: "Gasco", text: "Destaca-se muito acima da média. Capaz de desbloquear problemas com muita velocidade e excelente integração de equipes." },
  { name: "José Luis Paredes", role: "Inovação Corporativa", company: "Gasco", text: "Excelente profissional capaz de ler as demandas dos usuários e traduzi-las exatamente naquilo de que realmente precisam." },
  { name: "Elizabeth Farías", role: "Engenheira QA", company: "Gasco", text: "As reuniões de equipe nunca eram maçantes. Ele é empático, com incrível paciência e sempre disposto a motivar a todos." },
  { name: "Stiwart Tobías", role: "CEO & Full Stack Dev", company: "Gasco", text: "Líder excepcional e Scrum Master altamente competente. Sua experiência foi chave para o sucesso dos nossos projetos." },
  { name: "Erika Ramirez", role: "Product Designer UX/UI", company: "Gasco", text: "Líder natural que com sua proatividade sempre encontra oportunidades. Que privilégio trabalhar ao lado dele." },
  { name: "Pablo Leiva", role: "Project Manager", company: "Cencosud Scotiabank", text: "Sempre preocupado com a parte técnica e humana. Um excelente líder e conhecedor para enfrentar qualquer desafio." },
  { name: "Zulay Sánchez", role: "Gestão de Mudanças", company: "RedSalud CCHC", text: "Ele promove espaços inovadores voltados à melhoria contínua. Trabalhar com ele foi excelente, altamente orientado a metas." },
  { name: "Marianella Rojas", role: "Engenheira de Sistemas", company: "Cencosud Scotiabank", text: "Alto desempenho e adaptabilidade. Suas capacidades para gerenciamento ágil de conflitos em situações difíceis são valiosas." },
  { name: "Deyanny Prado", role: "Product Owner", company: "Cencosud Scotiabank", text: "Um profissional sempre aberto e muito focado no aprendizado. Demonstrou imensa empatia ao longo dos nossos desafios." },
  { name: "Juan Carlos Toro", role: "QA Lead", company: "Cencosud Scotiabank", text: "Sempre disposto a destravar problemas de modo certeiro, colocando seu profundo saber técnico e metodológico nativo." },
  { name: "Rafael Moya", role: "Desenvolvimento Organizacional", company: "Cencosud Scotiabank", text: "Fortemente engajado com sua equipe e muito consciente de estimular relações duradouras que constroem laços sólidos." },
  { name: "Percy Ross", role: "Gestor Projetos TI", company: "Cencosud Scotiabank", text: "Um grande líder e muito motivador, que trabalha com sinergia mantendo sólidos conhecimentos da última tecnologia de vanguarda." },
  { name: "Richard Barbera", role: "CTO / Diretor de Engenharia", company: "Cencosud Scotiabank", text: "Metódico, super organizado e voltado para times. Altamente recomendado para projetos digitais de alto envolvimento." },
  { name: "Reinaldo Gonzalez", role: "Chefe de Modernização", company: "Cencosud Scotiabank", text: "Sempre atualizado com as novas tendências de metodologias e inovação, evidenciando incrível talento em gestão tecnológica." },
  { name: "William Gómez", role: "Líder Técnico", company: "Innomar Ltda", text: "Grande capacidade analítica; acompanha os objetivos sendo sempre facilitador ágil nas situações mais complexas de sistemas." },
  { name: "Gonzalo Sánchez", role: "Desenvolvedor Full Stack", company: "Cencosud S.A.", text: "Notavelmente responsável e sempre demonstrando incrível domínio na essência natural das metodologias ágeis de mercado." },
  { name: "Paulina Barrera", role: "Product Manager", company: "Cencosud Scotiabank", text: "Muito pró-ativo e bastante motivado para promover inovação profunda com a capacidade constante de aportar tecnologicamente nos times." }
];
